package com.carlos.controlmedicamentos

import androidx.compose.foundation.pager.PagerState
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import com.carlos.controlmedicamentos.data.local.*
import com.carlos.controlmedicamentos.data.remote.VademecumMedication

@Composable
internal fun MedicamentoFormBodyEscritorio(
    modifier: Modifier = Modifier,
    s: MedicamentoFormState,
    callbacks: MedicamentoFormCallbacks,
    launchers: FormLaunchers,
    pacienteActivo: PatientProfile?,
    perfilesPacientes: List<PatientProfile>,
    insumosGuardados: List<Medication>,
    embarazoActivo: ControlEmbarazo?,
    ninosDelPaciente: List<NinoEntity>,
    pagerEscritorioState: PagerState,
    paginaBaseEscritorio: Int,
    fechaBaseEscritorio: Long,
    fechaResumenEscritorioTexto: String,
    escritorioEsHoy: Boolean,
    database: AppDatabase,
    fallAlertPanelState: MutableState<Boolean>
) {
    EscritorioContent(
        modifier = modifier,
        pacienteActivo = pacienteActivo,
        insumosGuardados = insumosGuardados,
        perfilesPacientes = perfilesPacientes,
        pagerEscritorioState = pagerEscritorioState,
        paginaBaseEscritorio = paginaBaseEscritorio,
        fechaBaseEscritorio = fechaBaseEscritorio,
        fechaResumenEscritorioTexto = fechaResumenEscritorioTexto,
        escritorioEsHoy = escritorioEsHoy,
        tomaPendienteDeEliminarState = s.tomaPendienteDeEliminarState,
        mostrarDialogoMediaState = s.mostrarDialogoMediaState,
        formularioInformeAutoAbiertoState = s.formularioInformeAutoAbiertoState,
        database = database,
        mostrarMenuHamburguesaState = s.mostrarMenuHamburguesaState,
        embarazoActivo = embarazoActivo,
        ninosDelPaciente = ninosDelPaciente,
        alarmaSonidoUriState = s.alarmaSonidoUriState,
        alarmaSonidoNombreState = s.alarmaSonidoNombreState,
        fallAlertPanelState = fallAlertPanelState,
        intervaloReintentoSeleccionadoState = s.intervaloReintentoSeleccionadoState,
        numeroIntentosCriticosSeleccionadoState = s.numeroIntentosCriticosSeleccionadoState,
        tienePermisoCamara = s.tienePermisoCamara,
        cameraPermissionLauncher = launchers.cameraPermissionLauncher,
        pickStudyImagesLauncher = launchers.pickStudyImagesLauncher,
        onAbrirNuevaFichaPaciente = callbacks.onAbrirNuevaFichaPaciente,
        onAbrirFichaPaciente = callbacks.onAbrirFichaPaciente,
        onCerrarPanelesSecundarios = callbacks.onCerrarPanelesSecundarios,
        onResetForm = callbacks.onResetForm,
        onMostrarFormulario = { s.mostrarFormularioState.value = it },
        onMostrarPanelPacientes = { s.mostrarPanelPacientesState.value = it },
        onMostrarPanelProfesionales = { s.mostrarPanelProfesionalesState.value = it },
        onMostrarPanelInformes = { s.mostrarPanelInformesState.value = it },
        onMostrarListaInsumos = { s.mostrarListaInsumosState.value = it },
        onMostrarDialogoMedia = { s.mostrarDialogoMediaState.value = it },
        onMostrarPanelSignosVitales = callbacks.onMostrarPanelSignosVitalesInit,
        onMostrarPanelConfiguracionAlertas = { s.mostrarPanelConfiguracionAlertasState.value = it },
        onMostrarPanelAsistenteIa = { s.mostrarPanelAsistenteIaState.value = it },
        onMostrarPanelPodometro = { s.mostrarPanelPodometroState.value = it },
        onMostrarPanelPedidos = { s.mostrarPanelPedidosState.value = it },
        onMostrarPanelBackups = { s.mostrarPanelBackupsState.value = it },
        onMostrarPanelHidratacion = { s.mostrarPanelHidratacionState.value = it },
        onMostrarPanelCicloMenstrual = { s.mostrarPanelCicloMenstrualState.value = it },
        onMostrarPanelAnticonceptivos = { s.mostrarPanelAnticonceptivosState.value = it },
        onMostrarPanelEmbarazo = { s.mostrarPanelEmbarazoState.value = it },
        onMostrarPanelPediatrico = { s.mostrarPanelPediatricoState.value = it },
        onMostrarPanelReporteClinico = { s.mostrarPanelReporteClinicoState.value = it },
        onMostrarPanelEstadisticas = { s.mostrarPanelEstadisticasState.value = it },
        onMostrarPanelVerificadorTomas = { s.mostrarPanelVerificadorTomasState.value = it },
        onMostrarPanelDiario = { s.mostrarPanelDiarioState.value = it },
        onMostrarPanelSedentarismo = { s.mostrarPanelSedentarismoState.value = it },
        onMostrarPanelDentista = { s.mostrarPanelDentistaState.value = it },
        onResolveAlarmSoundLabel = callbacks.onResolveAlarmSoundLabel,
        onInsumoARecargar = { med -> s.inputRecargarStockState.value = ""; s.insumoARecargarState.value = med },
        onInsumoAPedir = { med -> s.inputUnidadesPedidoState.value = ""; s.insumoAPedirState.value = med },
        onInsumoSeleccionado = { s.insumoSeleccionadoEnInventarioState.value = it },
        onMostrarListaInsumosView = { s.mostrarListaInsumosState.value = it },
        onCameraPermissionPendingChange = { s.cameraPermissionPendingState.value = it },
        onMostrarPanelInformesChange = { s.mostrarPanelInformesState.value = it },
        onMostrarFormularioInformeChange = { s.mostrarFormularioInformeState.value = it },
        onFormatHour = callbacks.onFormatHour,
        onMoverFecha = callbacks.onMoverFecha
    )
}
